Remove Hyrax::BasicMetadata for AllinsonFlex
notch8/utk-hyku pull request #123
Opened 2022-10-26 05:04 UTC by orangewolf

# Summary
Addresses #199 by removing Hyrax::BasicMetadata and modifying AllinsonFlex to temporarily define attributes which cannot be adequately supported as required in Hyrax via dynamic schema.

# Screenshots / Video

# Expected Behavior

# Notes

If you need further information on how to fill this out, read the [playbook](https://playbook-staging.notch8.com/en/notch8/process/merge-requests)

2022-11-04 21:58 UTC, ShanaLMoore commented on Gemfile.lock
> +  revision: 96b7c48da97698c4d09c63f9b8b1fcbe1f763b49
bundle update allinson_flex --conservative 

We should only see an update to the revision in gemfile.lock

2022-11-04 23:54 UTC, ShanaLMoore requested changes
Nice work. This looks to be working.

Locally I reverted the last two commits, updated allinson flex conservatively, corrected a rubocop issue, and needed to remove [this](https://github.com/scientist-softserv/utk-hyku/blob/main/app/indexers/app_indexer.rb#L10) line in order to successfully save any work type. 

ref: https://github.com/scientist-softserv/utk-hyku/pull/168/files

2022-11-07 21:44 UTC, laritakr commented
> #### ⚠️ GitGuardian has uncovered 2 secrets following the scan of your pull request.
> Please consider investigating the findings and remediating the incidents. Failure to do so may lead to compromising the associated services or software components.
> 
> 🔎 Detected hardcoded secrets in your pull request
> 🛠 Guidelines to remediate hardcoded secrets
> 🦉 [GitGuardian](https://dashboard.gitguardian.com/auth/login/?utm_medium=checkruns&utm_source=github&utm_campaign=cr1) detects secrets in your source code to help developers and security teams secure the modern development process. You are seeing this because you or someone else with access to this repository has authorized GitGuardian to scan your pull request.Our GitHub checks need improvements? [Share your feedbacks](https://050127dayho.typeform.com/to/KmeAPTMk)!

These secrets warnings are brought back in due to merging the main branch updates into my branch. Nothing I changed included any secrets.

2022-11-07 21:56 UTC, ShanaLMoore approved these changes

2022-11-07 21:56 UTC, ShanaLMoore commented on app/indexers/app_indexer.rb
> +  # include Hyrax::IndexesLinkedMetadata
👍🏿

2022-11-07 21:56 UTC, ShanaLMoore commented on app/indexers/attachment_indexer.rb
> -  # This indexes the default metadata. You can remove it if you want to
👍🏿

2022-11-07 21:56 UTC, ShanaLMoore commented on Gemfile.lock
> +  revision: 96b7c48da97698c4d09c63f9b8b1fcbe1f763b49
👍🏿

2022-11-07 22:03 UTC, merged