I150 destroy attachments and filesets
notch8/utk-hyku pull request #179
Opened 2022-11-09 04:43 UTC by kirkkwang

refs #150 

- destroy `Attachments` and their `FileSets` if they don't have a parent work

Currently, when a work that has an `Attachment` child work gets deleted, the `Attachment` gets orphaned and persists in the database.

This change will destroy the `Attachment` as well as its `FileSet` when it has no more parent works.

2022-11-09 18:17 UTC, alishaevn approved these changes

2022-11-09 21:04 UTC, laritakr requested changes
What happens if we have a work that contains another work that is NOT an Attachment? I think we want a spec for that condition as well. Otherwise looks great.

2022-11-10 14:56 UTC, laritakr approved these changes

2022-11-10 14:57 UTC, laritakr commented
Looks great!

2022-11-10 14:59 UTC, merged