use 0.0.4 tag for actions library
notch8/utk-hyku pull request #209
Opened 2022-11-17 19:47 UTC by labradford

Fixes #issuenumber ; refs #issuenumber

Present tense short summary (50 characters or less)

More detailed description, if necessary. Try to be as descriptive as you can: even if you think that the PR content is obvious, it may not be obvious to others. Include tracebacks if helpful, and be sure to call out any bits of the PR that may be work-in-progress.

Description can have multiple paragraphs and you can use code examples inside:

``` ruby
class PostsController
  def index
    respond_with Post.limit(10)
  end
end
```

Changes proposed in this pull request:
*
*
*

@samvera/hyku-code-reviewers

2022-11-17 20:14 UTC, bkiahstroud requested changes

2022-11-17 20:14 UTC, bkiahstroud commented on .github/workflows/build-test-lint.yaml
> +    uses: scientist-softserv/actions/.github/workflows/test.yaml@v0.0.3
`test.yaml@v0.0.4` should work now; see https://github.com/scientist-softserv/actions/pull/15

2022-11-22 07:36 UTC, orangewolf commented
@bkiahstroud can I get an updated review and if you approve merge?

2022-11-22 18:00 UTC, bkiahstroud approved these changes

2022-11-22 18:01 UTC, bkiahstroud commented on .github/workflows/build-test-lint.yaml
> +    secrets: inherit
@orangewolf this looks good to me, I do have a question though -- do we need `secrets: inherit` for the test and lint stages, or just build?

2022-11-22 18:53 UTC, orangewolf commented on .github/workflows/build-test-lint.yaml
> +    secrets: inherit
so far just build. we should only send secrets to steps that need them. I did not catch when modifying this PR that those were there.

2022-11-22 18:54 UTC, merged

2022-11-22 18:54 UTC, orangewolf commented
went ahead and merged this since all i did was remove an unused line